db:
  dsn: "root:wen123...@tcp(127.0.0.1:3306)/mall_user?charset=utf8mb4&parseTime=true&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

kafka:
  addrs:
    - "127.0.0.1:9094"

grpc:
  port: 8081
  etcdAddrs:
    - "127.0.0.1:2379"
