// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/order/grpc"
	"github.com/rermrf/mall/order/ioc"
	"github.com/rermrf/mall/order/repository"
	"github.com/rermrf/mall/order/repository/cache"
	"github.com/rermrf/mall/order/repository/dao"
	"github.com/rermrf/mall/order/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	orderDAO := dao.NewOrderDAO(db)
	cmdable := ioc.InitRedis()
	orderCache := cache.NewOrderCache(cmdable)
	orderRepository := repository.NewOrderRepository(orderDAO, orderCache)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	idempotencyService := ioc.InitIdempotencyService(cmdable)
	node := ioc.InitSnowflakeNode()
	clientv3Client := ioc.InitEtcdClient()
	productServiceClient := ioc.InitProductClient(clientv3Client)
	inventoryServiceClient := ioc.InitInventoryClient(clientv3Client)
	paymentServiceClient := ioc.InitPaymentClient(clientv3Client)
	userServiceClient := ioc.InitUserClient(clientv3Client)
	logger := ioc.InitLogger()
	orderService := service.NewOrderService(orderRepository, producer, idempotencyService, node, productServiceClient, inventoryServiceClient, paymentServiceClient, userServiceClient, logger)
	orderGRPCServer := grpc.NewOrderGRPCServer(orderService)
	server := ioc.InitGRPCServer(orderGRPCServer, logger)
	consumerGroup := ioc.InitConsumerGroup(client)
	orderPaidConsumer := ioc.NewOrderPaidConsumer(consumerGroup, logger, orderService)
	orderCloseDelayConsumer := ioc.NewOrderCloseDelayConsumer(consumerGroup, logger, orderService)
	seckillSuccessConsumer := ioc.NewSeckillSuccessConsumer(consumerGroup, logger, orderService, userServiceClient)
	v := ioc.InitConsumers(orderPaidConsumer, orderCloseDelayConsumer, seckillSuccessConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitProductClient, ioc.InitInventoryClient, ioc.InitPaymentClient, ioc.InitUserClient, ioc.InitIdempotencyService, ioc.InitSnowflakeNode)

var orderSet = wire.NewSet(dao.NewOrderDAO, cache.NewOrderCache, repository.NewOrderRepository, service.NewOrderService, grpc.NewOrderGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitConsumerGroup, ioc.NewOrderPaidConsumer, ioc.NewOrderCloseDelayConsumer, ioc.NewSeckillSuccessConsumer, ioc.InitConsumers, ioc.InitGRPCServer)
