// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/payment/grpc"
	"github.com/rermrf/mall/payment/ioc"
	"github.com/rermrf/mall/payment/repository"
	"github.com/rermrf/mall/payment/repository/cache"
	"github.com/rermrf/mall/payment/repository/dao"
	"github.com/rermrf/mall/payment/service"
	"github.com/rermrf/mall/payment/service/channel"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	paymentDAO := dao.NewPaymentDAO(db)
	cmdable := ioc.InitRedis()
	paymentCache := cache.NewPaymentCache(cmdable)
	paymentRepository := repository.NewPaymentRepository(paymentDAO, paymentCache)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	idempotencyService := ioc.InitIdempotencyService(cmdable)
	node := ioc.InitSnowflakeNode()
	clientv3Client := ioc.InitEtcdClient()
	orderServiceClient := ioc.InitOrderClient(clientv3Client)
	refundSyncer := service.NewOrderRefundSyncer(orderServiceClient)
	mockChannel := channel.NewMockChannel(node)
	alipayClient := ioc.InitAlipayClient()
	alipayChannel := channel.NewAlipayChannel(alipayClient)
	wechatConfig := ioc.InitWechatConfig()
	coreClient := ioc.InitWechatClient(wechatConfig)
	wechatChannel := channel.NewWechatChannel(coreClient, wechatConfig)
	logger := ioc.InitLogger()
	paymentService := service.NewPaymentService(paymentRepository, producer, idempotencyService, node, refundSyncer, mockChannel, alipayChannel, wechatChannel, logger)
	reconciliationDAO := dao.NewReconciliationDAO(db)
	reconciliationService := service.NewReconciliationService(reconciliationDAO, paymentRepository, mockChannel, alipayChannel, wechatChannel, node, logger)
	paymentGRPCServer := grpc.NewPaymentGRPCServer(paymentService, reconciliationService)
	server := ioc.InitGRPCServer(paymentGRPCServer, logger)
	reconciliationJob := service.NewReconciliationJob(reconciliationService, logger)
	app := &App{
		Server:   server,
		ReconJob: reconciliationJob,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitOrderClient, ioc.InitIdempotencyService, ioc.InitSnowflakeNode)

var paymentSet = wire.NewSet(dao.NewPaymentDAO, dao.NewReconciliationDAO, cache.NewPaymentCache, repository.NewPaymentRepository, channel.NewMockChannel, ioc.InitAlipayClient, channel.NewAlipayChannel, ioc.InitWechatConfig, ioc.InitWechatClient, channel.NewWechatChannel, service.NewOrderRefundSyncer, service.NewPaymentService, service.NewReconciliationService, service.NewReconciliationJob, grpc.NewPaymentGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitGRPCServer)
