// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/payment/grpc"
	"github.com/rermrf/mall/payment/ioc"
	"github.com/rermrf/mall/payment/repository"
	"github.com/rermrf/mall/payment/repository/cache"
	"github.com/rermrf/mall/payment/repository/dao"
	"github.com/rermrf/mall/payment/service"
	"github.com/rermrf/mall/payment/service/channel"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	paymentDAO := dao.NewPaymentDAO(db)
	cmdable := ioc.InitRedis()
	paymentCache := cache.NewPaymentCache(cmdable)
	paymentRepository := repository.NewPaymentRepository(paymentDAO, paymentCache)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	idempotencyService := ioc.InitIdempotencyService(cmdable)
	node := ioc.InitSnowflakeNode()
	mockChannel := channel.NewMockChannel(node)
	alipayClient := ioc.InitAlipayClient()
	alipayChannel := channel.NewAlipayChannel(alipayClient)
	logger := ioc.InitLogger()
	paymentService := service.NewPaymentService(paymentRepository, producer, idempotencyService, node, mockChannel, alipayChannel, logger)
	paymentGRPCServer := grpc.NewPaymentGRPCServer(paymentService)
	server := ioc.InitGRPCServer(paymentGRPCServer, logger)
	app := &App{
		Server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitIdempotencyService, ioc.InitSnowflakeNode)

var paymentSet = wire.NewSet(dao.NewPaymentDAO, cache.NewPaymentCache, repository.NewPaymentRepository, channel.NewMockChannel, ioc.InitAlipayClient, channel.NewAlipayChannel, service.NewPaymentService, grpc.NewPaymentGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitGRPCServer)
