// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/search/grpc"
	"github.com/rermrf/mall/search/ioc"
	"github.com/rermrf/mall/search/repository"
	"github.com/rermrf/mall/search/repository/cache"
	"github.com/rermrf/mall/search/repository/dao"
	"github.com/rermrf/mall/search/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitES()
	searchDAO := dao.NewSearchDAO(client)
	cmdable := ioc.InitRedis()
	searchCache := cache.NewSearchCache(cmdable)
	searchRepository := repository.NewSearchRepository(searchDAO, searchCache)
	logger := ioc.InitLogger()
	searchService := service.NewSearchService(searchRepository, logger)
	searchGRPCServer := grpc.NewSearchGRPCServer(searchService)
	server := ioc.InitGRPCServer(searchGRPCServer, logger)
	saramaClient := ioc.InitKafka()
	consumerGroup := ioc.InitConsumerGroup(saramaClient)
	clientv3Client := ioc.InitEtcdClient()
	productServiceClient := ioc.InitProductClient(clientv3Client)
	productUpdatedConsumer := ioc.NewProductUpdatedConsumer(consumerGroup, logger, productServiceClient, searchService)
	productStatusChangedConsumer := ioc.NewProductStatusChangedConsumer(consumerGroup, logger, productServiceClient, searchService)
	v := ioc.InitConsumers(productUpdatedConsumer, productStatusChangedConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitES, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitProductClient)

var searchSet = wire.NewSet(dao.NewSearchDAO, cache.NewSearchCache, repository.NewSearchRepository, service.NewSearchService, grpc.NewSearchGRPCServer, ioc.InitGRPCServer, ioc.InitConsumerGroup, ioc.NewProductUpdatedConsumer, ioc.NewProductStatusChangedConsumer, ioc.InitConsumers)
