// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/inventory/grpc"
	"github.com/rermrf/mall/inventory/ioc"
	"github.com/rermrf/mall/inventory/repository"
	"github.com/rermrf/mall/inventory/repository/cache"
	"github.com/rermrf/mall/inventory/repository/dao"
	"github.com/rermrf/mall/inventory/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	inventoryDAO := dao.NewInventoryDAO(db)
	cmdable := ioc.InitRedis()
	inventoryCache := cache.NewInventoryCache(cmdable)
	inventoryRepository := repository.NewInventoryRepository(inventoryDAO, inventoryCache)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	logger := ioc.InitLogger()
	inventoryService := service.NewInventoryService(inventoryRepository, producer, logger)
	inventoryGRPCServer := grpc.NewInventoryGRPCServer(inventoryService)
	server := ioc.InitGRPCServer(inventoryGRPCServer, logger)
	consumerGroup := ioc.InitConsumerGroup(client)
	deductExpireConsumer := ioc.NewDeductExpireConsumer(consumerGroup, logger, inventoryService)
	v := ioc.InitConsumers(deductExpireConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger)

var inventorySet = wire.NewSet(dao.NewInventoryDAO, cache.NewInventoryCache, repository.NewInventoryRepository, service.NewInventoryService, grpc.NewInventoryGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitConsumerGroup, ioc.NewDeductExpireConsumer, ioc.InitConsumers, ioc.InitGRPCServer)
