// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/cart/grpc"
	"github.com/rermrf/mall/cart/ioc"
	"github.com/rermrf/mall/cart/repository"
	"github.com/rermrf/mall/cart/repository/cache"
	"github.com/rermrf/mall/cart/repository/dao"
	"github.com/rermrf/mall/cart/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	cartDAO := dao.NewCartDAO(db)
	cmdable := ioc.InitRedis()
	cartCache := cache.NewCartCache(cmdable)
	cartRepository := repository.NewCartRepository(cartDAO, cartCache)
	logger := ioc.InitLogger()
	cartService := service.NewCartService(cartRepository, logger)
	cartGRPCServer := grpc.NewCartGRPCServer(cartService)
	server := ioc.InitGRPCServer(cartGRPCServer, logger)
	app := &App{
		Server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitEtcdClient)

var cartSet = wire.NewSet(dao.NewCartDAO, cache.NewCartCache, repository.NewCartRepository, service.NewCartService, grpc.NewCartGRPCServer, ioc.InitGRPCServer)
