// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/account/grpc"
	"github.com/rermrf/mall/account/ioc"
	"github.com/rermrf/mall/account/repository"
	"github.com/rermrf/mall/account/repository/cache"
	"github.com/rermrf/mall/account/repository/dao"
	"github.com/rermrf/mall/account/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	accountDAO := dao.NewAccountDAO(db)
	cmdable := ioc.InitRedis()
	accountCache := cache.NewAccountCache(cmdable)
	accountRepository := repository.NewAccountRepository(accountDAO, accountCache)
	client := ioc.InitEtcdClient()
	tenantServiceClient := ioc.InitTenantClient(client)
	tenantIntegration := ioc.InitTenantIntegration(tenantServiceClient)
	node := ioc.InitSnowflakeNode()
	logger := ioc.InitLogger()
	accountService := service.NewAccountService(accountRepository, tenantIntegration, node, logger)
	accountGRPCServer := grpc.NewAccountGRPCServer(accountService)
	server := ioc.InitGRPCServer(accountGRPCServer, logger)
	saramaClient := ioc.InitKafka()
	consumerGroup := ioc.InitConsumerGroup(saramaClient)
	orderCompletedConsumer := ioc.NewOrderCompletedConsumer(consumerGroup, logger, accountService)
	v := ioc.InitConsumers(orderCompletedConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitSnowflakeNode)

var accountSet = wire.NewSet(dao.NewAccountDAO, cache.NewAccountCache, repository.NewAccountRepository, service.NewAccountService, grpc.NewAccountGRPCServer, ioc.InitConsumerGroup, ioc.NewOrderCompletedConsumer, ioc.InitConsumers, ioc.InitTenantClient, ioc.InitTenantIntegration, ioc.InitGRPCServer)
