// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/marketing/grpc"
	"github.com/rermrf/mall/marketing/ioc"
	"github.com/rermrf/mall/marketing/repository"
	"github.com/rermrf/mall/marketing/repository/cache"
	"github.com/rermrf/mall/marketing/repository/dao"
	"github.com/rermrf/mall/marketing/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	couponDAO := dao.NewCouponDAO(db)
	userCouponDAO := dao.NewUserCouponDAO(db)
	seckillDAO := dao.NewSeckillDAO(db)
	promotionDAO := dao.NewPromotionDAO(db)
	cmdable := ioc.InitRedis()
	marketingCache := cache.NewMarketingCache(cmdable)
	marketingRepository := repository.NewMarketingRepository(couponDAO, userCouponDAO, seckillDAO, promotionDAO, marketingCache)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	logger := ioc.InitLogger()
	marketingService := service.NewMarketingService(marketingRepository, producer, logger)
	marketingGRPCServer := grpc.NewMarketingGRPCServer(marketingService)
	server := ioc.InitGRPCServer(marketingGRPCServer, logger)
	consumerGroup := ioc.InitConsumerGroup(client)
	clientv3Client := ioc.InitEtcdClient()
	orderServiceClient := ioc.InitOrderClient(clientv3Client)
	orderCancelledConsumer := ioc.NewOrderCancelledConsumer(consumerGroup, logger, marketingService, orderServiceClient)
	v := ioc.InitConsumers(orderCancelledConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitOrderClient)

var marketingSet = wire.NewSet(dao.NewCouponDAO, dao.NewUserCouponDAO, dao.NewSeckillDAO, dao.NewPromotionDAO, cache.NewMarketingCache, repository.NewMarketingRepository, service.NewMarketingService, grpc.NewMarketingGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitGRPCServer, ioc.InitConsumerGroup, ioc.NewOrderCancelledConsumer, ioc.InitConsumers)
