server:
  addr: ":8080"

etcd:
  addrs:
    - "127.0.0.1:2379"

redis:
  addr: "127.0.0.1:6379"

jwt:
  accessSecret: "consumer-bff-access-secret-key32!"
  refreshSecret: "consumer-bff-refresh-secret-key32!"

