// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/tenant/grpc"
	"github.com/rermrf/mall/tenant/ioc"
	"github.com/rermrf/mall/tenant/repository"
	"github.com/rermrf/mall/tenant/repository/cache"
	"github.com/rermrf/mall/tenant/repository/dao"
	"github.com/rermrf/mall/tenant/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	tenantDAO := dao.NewTenantDAO(db)
	planDAO := dao.NewPlanDAO(db)
	quotaDAO := dao.NewQuotaDAO(db)
	shopDAO := dao.NewShopDAO(db)
	cmdable := ioc.InitRedis()
	tenantCache := cache.NewTenantCache(cmdable)
	logger := ioc.InitLogger()
	tenantRepository := repository.NewTenantRepository(tenantDAO, planDAO, quotaDAO, shopDAO, tenantCache, logger)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	tenantService := service.NewTenantService(tenantRepository, producer, logger)
	tenantGRPCServer := grpc.NewTenantGRPCServer(tenantService)
	server := ioc.InitGRPCServer(tenantGRPCServer, logger)
	app := &App{
		Server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger)

var tenantSet = wire.NewSet(dao.NewTenantDAO, dao.NewPlanDAO, dao.NewQuotaDAO, dao.NewShopDAO, cache.NewTenantCache, repository.NewTenantRepository, service.NewTenantService, grpc.NewTenantGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitGRPCServer)
