// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/logistics/grpc"
	"github.com/rermrf/mall/logistics/ioc"
	"github.com/rermrf/mall/logistics/repository"
	"github.com/rermrf/mall/logistics/repository/cache"
	"github.com/rermrf/mall/logistics/repository/dao"
	"github.com/rermrf/mall/logistics/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	freightTemplateDAO := dao.NewFreightTemplateDAO(db)
	shipmentDAO := dao.NewShipmentDAO(db)
	shipmentTrackDAO := dao.NewShipmentTrackDAO(db)
	cmdable := ioc.InitRedis()
	logisticsCache := cache.NewLogisticsCache(cmdable)
	logisticsRepository := repository.NewLogisticsRepository(freightTemplateDAO, shipmentDAO, shipmentTrackDAO, logisticsCache)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	logger := ioc.InitLogger()
	logisticsService := service.NewLogisticsService(logisticsRepository, producer, logger)
	logisticsGRPCServer := grpc.NewLogisticsGRPCServer(logisticsService)
	server := ioc.InitGRPCServer(logisticsGRPCServer, logger)
	app := &App{
		Server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient)

var logisticsSet = wire.NewSet(dao.NewFreightTemplateDAO, dao.NewShipmentDAO, dao.NewShipmentTrackDAO, cache.NewLogisticsCache, repository.NewLogisticsRepository, service.NewLogisticsService, grpc.NewLogisticsGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitGRPCServer)
