// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/notification/grpc"
	"github.com/rermrf/mall/notification/ioc"
	"github.com/rermrf/mall/notification/repository"
	"github.com/rermrf/mall/notification/repository/cache"
	"github.com/rermrf/mall/notification/repository/dao"
	"github.com/rermrf/mall/notification/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	notificationTemplateDAO := dao.NewNotificationTemplateDAO(db)
	notificationDAO := dao.NewNotificationDAO(db)
	cmdable := ioc.InitRedis()
	notificationCache := cache.NewNotificationCache(cmdable)
	notificationRepository := repository.NewNotificationRepository(notificationTemplateDAO, notificationDAO, notificationCache)
	smsProvider := ioc.InitSmsProvider()
	emailProvider := ioc.InitEmailProvider()
	logger := ioc.InitLogger()
	notificationService := service.NewNotificationService(notificationRepository, smsProvider, emailProvider, logger)
	notificationGRPCServer := grpc.NewNotificationGRPCServer(notificationService)
	server := ioc.InitGRPCServer(notificationGRPCServer, logger)
	client := ioc.InitKafka()
	consumerGroup := ioc.InitConsumerGroup(client)
	userRegisteredConsumer := ioc.NewUserRegisteredConsumer(consumerGroup, logger, notificationService)
	clientv3Client := ioc.InitEtcdClient()
	orderServiceClient := ioc.InitOrderClient(clientv3Client)
	orderPaidConsumer := ioc.NewOrderPaidConsumer(consumerGroup, logger, notificationService, orderServiceClient)
	orderShippedConsumer := ioc.NewOrderShippedConsumer(consumerGroup, logger, notificationService, orderServiceClient)
	inventoryAlertConsumer := ioc.NewInventoryAlertConsumer(consumerGroup, logger, notificationService)
	tenantApprovedConsumer := ioc.NewTenantApprovedConsumer(consumerGroup, logger, notificationService)
	tenantPlanChangedConsumer := ioc.NewTenantPlanChangedConsumer(consumerGroup, logger, notificationService)
	orderCompletedConsumer := ioc.NewOrderCompletedConsumer(consumerGroup, logger, notificationService, orderServiceClient)
	v := ioc.InitConsumers(userRegisteredConsumer, orderPaidConsumer, orderShippedConsumer, inventoryAlertConsumer, tenantApprovedConsumer, tenantPlanChangedConsumer, orderCompletedConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitOrderClient)

var notificationSet = wire.NewSet(dao.NewNotificationTemplateDAO, dao.NewNotificationDAO, cache.NewNotificationCache, repository.NewNotificationRepository, service.NewNotificationService, grpc.NewNotificationGRPCServer, ioc.InitSmsProvider, ioc.InitEmailProvider, ioc.InitGRPCServer, ioc.InitConsumerGroup, ioc.NewUserRegisteredConsumer, ioc.NewOrderPaidConsumer, ioc.NewOrderShippedConsumer, ioc.NewInventoryAlertConsumer, ioc.NewTenantApprovedConsumer, ioc.NewTenantPlanChangedConsumer, ioc.NewOrderCompletedConsumer, ioc.InitConsumers)
