// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/product/grpc"
	"github.com/rermrf/mall/product/ioc"
	"github.com/rermrf/mall/product/repository"
	"github.com/rermrf/mall/product/repository/cache"
	"github.com/rermrf/mall/product/repository/dao"
	"github.com/rermrf/mall/product/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	productDAO := dao.NewProductDAO(db)
	skudao := dao.NewSKUDAO(db)
	specDAO := dao.NewSpecDAO(db)
	cmdable := ioc.InitRedis()
	productCache := cache.NewProductCache(cmdable)
	logger := ioc.InitLogger()
	productRepository := repository.NewProductRepository(productDAO, skudao, specDAO, productCache, db, logger)
	categoryDAO := dao.NewCategoryDAO(db)
	categoryRepository := repository.NewCategoryRepository(categoryDAO, productCache, logger)
	brandDAO := dao.NewBrandDAO(db)
	brandRepository := repository.NewBrandRepository(brandDAO, logger)
	client := ioc.InitEtcdClient()
	tenantServiceClient := ioc.InitTenantClient(client)
	saramaClient := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(saramaClient)
	producer := ioc.InitProducer(syncProducer)
	productService := service.NewProductService(productRepository, categoryRepository, brandRepository, tenantServiceClient, producer, logger)
	productGRPCServer := grpc.NewProductGRPCServer(productService)
	server := ioc.InitGRPCServer(productGRPCServer, logger)
	app := &App{
		Server: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitTenantClient)

var productSet = wire.NewSet(dao.NewProductDAO, dao.NewSKUDAO, dao.NewSpecDAO, dao.NewCategoryDAO, dao.NewBrandDAO, cache.NewProductCache, repository.NewProductRepository, repository.NewCategoryRepository, repository.NewBrandRepository, service.NewProductService, grpc.NewProductGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitGRPCServer)
