// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/merchant-bff/handler"
	"github.com/rermrf/mall/merchant-bff/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitEtcdClient()
	userServiceClient := ioc.InitUserClient(client)
	cmdable := ioc.InitRedis()
	jwtHandler := ioc.InitJWTHandler(userServiceClient, cmdable)
	logger := ioc.InitLogger()
	userHandler := handler.NewUserHandler(userServiceClient, logger)
	tenantServiceClient := ioc.InitTenantClient(client)
	tenantHandler := handler.NewTenantHandler(tenantServiceClient, logger)
	inventoryServiceClient := ioc.InitInventoryClient(client)
	inventoryHandler := handler.NewInventoryHandler(inventoryServiceClient, logger)
	orderServiceClient := ioc.InitOrderClient(client)
	orderHandler := handler.NewOrderHandler(orderServiceClient, logger)
	paymentServiceClient := ioc.InitPaymentClient(client)
	paymentHandler := handler.NewPaymentHandler(paymentServiceClient, logger)
	marketingServiceClient := ioc.InitMarketingClient(client)
	marketingHandler := handler.NewMarketingHandler(marketingServiceClient, logger)
	logisticsServiceClient := ioc.InitLogisticsClient(client)
	logisticsHandler := handler.NewLogisticsHandler(logisticsServiceClient, orderServiceClient, logger)
	notificationServiceClient := ioc.InitNotificationClient(client)
	notificationHandler := handler.NewNotificationHandler(notificationServiceClient, logger)
	productServiceClient := ioc.InitProductClient(client)
	productHandler := handler.NewProductHandler(productServiceClient, logger)
	engine := ioc.InitGinServer(jwtHandler, userHandler, tenantHandler, inventoryHandler, orderHandler, paymentHandler, marketingHandler, logisticsHandler, notificationHandler, productHandler, logger)
	app := &App{
		Server: engine,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitEtcdClient, ioc.InitLogger, ioc.InitRedis, ioc.InitUserClient, ioc.InitTenantClient, ioc.InitInventoryClient, ioc.InitOrderClient, ioc.InitPaymentClient, ioc.InitMarketingClient, ioc.InitLogisticsClient, ioc.InitNotificationClient, ioc.InitProductClient)

var handlerSet = wire.NewSet(ioc.InitJWTHandler, handler.NewUserHandler, handler.NewTenantHandler, handler.NewInventoryHandler, handler.NewOrderHandler, handler.NewPaymentHandler, handler.NewMarketingHandler, handler.NewLogisticsHandler, handler.NewNotificationHandler, handler.NewProductHandler, ioc.InitGinServer)
