// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/user/grpc"
	"github.com/rermrf/mall/user/ioc"
	"github.com/rermrf/mall/user/repository"
	"github.com/rermrf/mall/user/repository/cache"
	"github.com/rermrf/mall/user/repository/dao"
	"github.com/rermrf/mall/user/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	roleDAO := dao.NewRoleDAO(db)
	addressDAO := dao.NewAddressDAO(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	logger := ioc.InitLogger()
	userRepository := repository.NewUserRepository(userDAO, roleDAO, addressDAO, userCache, logger)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := ioc.InitProducer(syncProducer)
	userService := service.NewUserService(userRepository, producer, logger)
	userGRPCServer := grpc.NewUserGRPCServer(userService)
	server := ioc.InitGRPCServer(userGRPCServer, logger)
	consumerGroup := ioc.InitConsumerGroup(client)
	userRegisteredConsumer := ioc.NewUserRegisteredConsumer(consumerGroup, logger)
	v := ioc.InitConsumers(userRegisteredConsumer)
	app := &App{
		Server:    server,
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitKafka, ioc.InitLogger)

var userSet = wire.NewSet(dao.NewUserDAO, dao.NewRoleDAO, dao.NewAddressDAO, cache.NewUserCache, repository.NewUserRepository, service.NewUserService, grpc.NewUserGRPCServer, ioc.InitSyncProducer, ioc.InitProducer, ioc.InitConsumerGroup, ioc.NewUserRegisteredConsumer, ioc.InitConsumers, ioc.InitGRPCServer)
