// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rermrf/mall/consumer-bff/handler"
	"github.com/rermrf/mall/consumer-bff/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitEtcdClient()
	userServiceClient := ioc.InitUserClient(client)
	cmdable := ioc.InitRedis()
	jwtHandler := ioc.InitJWTHandler(userServiceClient, cmdable)
	logger := ioc.InitLogger()
	userHandler := handler.NewUserHandler(userServiceClient, logger)
	tenantServiceClient := ioc.InitTenantClient(client)
	tenantHandler := handler.NewTenantHandler(tenantServiceClient, logger)
	inventoryServiceClient := ioc.InitInventoryClient(client)
	inventoryHandler := handler.NewInventoryHandler(inventoryServiceClient, logger)
	orderServiceClient := ioc.InitOrderClient(client)
	orderHandler := handler.NewOrderHandler(orderServiceClient, logger)
	paymentServiceClient := ioc.InitPaymentClient(client)
	paymentHandler := handler.NewPaymentHandler(paymentServiceClient, orderServiceClient, logger)
	cartServiceClient := ioc.InitCartClient(client)
	productServiceClient := ioc.InitProductClient(client)
	cartHandler := handler.NewCartHandler(cartServiceClient, productServiceClient, logger)
	searchServiceClient := ioc.InitSearchClient(client)
	searchHandler := handler.NewSearchHandler(searchServiceClient, logger)
	marketingServiceClient := ioc.InitMarketingClient(client)
	marketingHandler := handler.NewMarketingHandler(marketingServiceClient, logger)
	logisticsServiceClient := ioc.InitLogisticsClient(client)
	logisticsHandler := handler.NewLogisticsHandler(logisticsServiceClient, orderServiceClient, logger)
	notificationServiceClient := ioc.InitNotificationClient(client)
	notificationHandler := handler.NewNotificationHandler(notificationServiceClient, logger)
	productHandler := handler.NewProductHandler(productServiceClient, logger)
	engine := ioc.InitGinServer(jwtHandler, userHandler, tenantHandler, inventoryHandler, orderHandler, paymentHandler, cartHandler, searchHandler, marketingHandler, logisticsHandler, notificationHandler, productHandler, tenantServiceClient, cmdable, logger)
	app := &App{
		Server: engine,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitEtcdClient, ioc.InitLogger, ioc.InitRedis, ioc.InitUserClient, ioc.InitTenantClient, ioc.InitInventoryClient, ioc.InitOrderClient, ioc.InitPaymentClient, ioc.InitCartClient, ioc.InitProductClient, ioc.InitSearchClient, ioc.InitMarketingClient, ioc.InitLogisticsClient, ioc.InitNotificationClient)

var handlerSet = wire.NewSet(ioc.InitJWTHandler, handler.NewUserHandler, handler.NewTenantHandler, handler.NewInventoryHandler, handler.NewOrderHandler, handler.NewPaymentHandler, handler.NewCartHandler, handler.NewSearchHandler, handler.NewMarketingHandler, handler.NewLogisticsHandler, handler.NewNotificationHandler, handler.NewProductHandler, ioc.InitGinServer)
