server:
  addr: ":8280"
etcd:
  addrs:
    - "127.0.0.1:2379"
redis:
  addr: "127.0.0.1:6379"
jwt:
  accessSecret: "admin-bff-access-secret-key-32b!"
  refreshSecret: "admin-bff-refresh-secret-key-32!"
